apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logs-viewer-web
spec:
  ingressClassName: traefik
  rules:
    # Replace with your Rocket.Chat public host.
    - host: rocketchat.example.com
      http:
        paths:
          - path: /logs-viewer
            pathType: Prefix
            backend:
              service:
                name: logs-viewer-web
                port:
                  number: 80
  tls:
    - hosts:
        - rocketchat.example.com
      secretName: rocketchat-tls
